name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Build
      run: make all

    - uses: actions/upload-artifact@master
      with:
        name: SwitchLua
        path: out/SwitchLua.nro
