name: Build

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'select branch to build (default: master)'
        required: false
        default: 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Build
      run: make all

    - uses: actions/upload-artifact@master
      with:
        name: SwitchLua
        path: SwitchLua.nro
